### ISSUE TITLE
Use std::sync::

### ISSUE THREAD

**Issue by yoshuawuyts** [leo60228/broadcaster#1]
Replaces `parking_lot::RwLock` with `std::sync::RwLock`, removing about 50% of dependencies in tree. Furthermore, `parking_lot`'s Mutex / RwLock APIs are set to become part of `std` and continued to be optimized there, so this sets us up to be somewhat future-proof. Thanks!

## Proposed

![2019-09-26-111127_1920x1080](https://user-images.githubusercontent.com/2467194/65675312-40c16d80-e04e-11e9-8a05-f4876616994f.png)

## Current

![2019-09-26-110930_1920x1080](https://user-images.githubusercontent.com/2467194/65675321-43bc5e00-e04e-11e9-8fd0-74986fd1a889.png)

**Comment by leo60228** [comment]
I originally was using std, but was getting pretty bad writer starvation in a program I was writing. Could you put this behind a feature?

**Comment by leo60228** [comment]
🤦‍♂️ I thought this was a PR, sorry.

**Comment by yoshuawuyts** [comment]
Oh lmao, so did I. I'm sorry

**Comment by yoshuawuyts** [comment]
this was def *meant* to be a PR

**Comment by yoshuawuyts** [comment]
Put it up in https://github.com/leo60228/broadcaster/pull/2. Going to patch it to be behind a feature (:
