### ISSUE TITLE
Use futures Stream/Sink trait?

### ISSUE THREAD

**Issue by stkfd** [leo60228/broadcaster#3]
Is there a particular reason I'm missing for using custom methods for receive and send?

My first naive try of replacing recv() with an implementation of Stream seems to work - although I've only run a very simple program and the included tests with it. Implementing Sink seems trickier but I don't think it's impossible.

The main benefit is obviously interoperability, and that you can use StreamExt/SinkExt to interact with the data.

**Comment by leo60228** [comment]
It wasn't necessary for my use-case, and I don't have experience writing raw futures code. You can PR it, if you want.

**Comment by stkfd** [comment]
Ah ok, wanted to make sure there wasn't a specific reason to do it this way that I was missing. I'll try out my forked version a bit more and give implementing Sink another try, then I might make a PR of it.

**Comment by leo60228** [comment]
I'd prefer you kept the current interface as well, but I'd be fine with them just being wrappers around the Stream/Sink impls.

**Comment by stkfd** [comment]
Yep definitely a good idea to keep backwards compatibility, will do that if i turn it into a PR
